MovieTask/MovieTask/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('firstapp.urls')),
    path('search/',include('searchapp.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

MovieTask/firstapp/urls.py
from . import views
from django.urls import path
app_name='firstapp'


urlpatterns = [
    path('',views.start,name='start'),
    path('register/',views.register,name='register'),
    # path('/',views.base,name='base'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('add/',views.add,name='add'),
    path('movie/<int:movie_id>/',views.details,name='details'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),

]

MovieTask/searchapp/urls.py
from  django.urls import path
from . import views

app_name='searchapp'

urlpatterns = [
    path('',views.SearchResult,name='SearchResult'),
]

MovieTask/firstapp/models.py
from django.db import models

# Create your models here.

class Topic(models.Model):
    category=models.CharField(max_length=240,unique=True)


    def __str__ (self):
        return '{}'.format(self.category)

class Film(models.Model):
    title=models.CharField(max_length=250)
    actors=models.TextField()
    img = models.ImageField(upload_to='gallery')
    desc=models.TextField()
    date=models.DateField()
    category=models.ForeignKey(Topic,on_delete=models.CASCADE)
    url=models.URLField(max_length=120)
    review = models.CharField(max_length=140, default='SOME STRING')
    rating = models.IntegerField(default=1)



    def __str__ (self):
        return '{}'.format(self.title)

MovieTask/searchapp/models.py
from django.db import models

# Create your models here.

MovieTask/firstapp/forms.py
from django import forms
from . models import Film,Topic

class FilmForm(forms.ModelForm):
    class Meta:
        model=Film
        fields=['title','actors','img','desc','date','category','review','rating','url']


class TopicForm(forms.ModelForm):
    class Meta:
        model=Topic
        fields=['category']

MovieTask/firstapp/views.py
from django.contrib import auth, messages
from django.contrib.auth.models import User
from django.shortcuts import render,redirect

from firstapp.forms import FilmForm,TopicForm

from firstapp.models import Film, Topic


# Create your views here.

def base(request):
   return render(request,'base.html')

def login(request):
    if request.method == 'POST':
        username=request.POST['username']
        pasword=request.POST['password']
        user=auth.authenticate(username=username,password=pasword)
        if user is not None:
            auth.login(request,user)
            return redirect('/')
        else:
            # messages.info('invalid user')
            return redirect('/')
    return render(request,'login.html')


def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        firstname = request.POST['firstname']
        lastname = request.POST['lastname']
        email = request.POST['email']
        password = request.POST['password']
        cpassword = request.POST['cpassword']
        if password == cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request,'username taken')
                return redirect('/register/')
            elif User.objects.filter(email=email).exists():
                messages.info(request,'email taken')
                return redirect('/register/')
            else:
                user=User.objects.create_user(username=username,first_name=firstname,last_name=lastname,email=email,password=password)
                user.save();
                return redirect('/')
                messages.info(request,'user created')
        else:
            messages.info(request,'password not matched')
            return  redirect('/')
            alert('registered succesfuly')
        return  redirect('/')
    return render(request,'register.html')



def logout(request):
    auth.logout(request)
    return redirect('/')

def start(request):
    obj=Film.objects.all()
    return render(request,'home.html',{'final':obj})


def add(request):

    if request.method == 'POST':
        title=request.POST.get('title',)
        desc = request.POST.get('desc',)
        date = request.POST.get('date',)
        actors = request.POST.get('actors', )
        category=Topic.objects.get(id=1)
        url = request.POST.get('url', )
        review=request.POST.get('review',)
        rating=request.POST.get('rating',)
        img = request.FILES['img']
        movies=Film(title=title,desc=desc,date=date,actors=actors,url=url,category=category,review=review,rating=rating,img=img)

        movies.save();
        # films.save();
        return redirect('/')
    return render(request,'add.html')



def details(request,movie_id):
    obj1=Film.objects.get(id=movie_id)
    # return HttpResponse('this is no %s' % movie_id)
    return render(request,'details.html',{'result':obj1})


def update(request,id):
    movie=Film.objects.get(id=id)
    form=FilmForm(request.POST or None,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'movie':movie,'form':form})

def delete(request,id):
    if request.method=='POST':
        movie=Film.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

MovieTask/searchapp/views.py
from django.shortcuts import render
from  firstapp.models import Film
from  django.db.models import Q
# Create your views here.

def SearchResult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Film.objects.all().filter(Q(title__contains=query) | Q(desc__contains=query))
        return render(request,'search.html',{'query':query,'products':products})

MovieTask/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form action="" method="POST" enctype="multipart/form-data">
     {% csrf_token %}
    <input type="text" name="title" placeholder="enter movie title"><br><br>
    <input type="text" name="desc" placeholder="enter movie description"><br><br>
    <input type="text" name="actors" placeholder="enter movie actors"><br><br>
    <input type="date" name="date" placeholder="enter movie date"><br><br>
    <label>Choose a category:</label>
     <select name="category" >
    <option value="Action">Action</option>
    <option value="Thriller">Thriller</option>
    <option value="Comedy">Comedy</option>
    <option value="FamilyEntertainer">FamilyEntertainer</option>
  </select><br><br>
    <input type="url" name="url" placeholder="enter movie link"><br><br>
    <input type="text" name="review" placeholder="movie review"><br><br>
    <input type="number" name="rating"placeholder="movie rating"><br><br>
    <input type="file" name="img"><br><br>
    <input type="submit">

</form>

{% endblock %}

MovieTask/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <a class="navbar-brand" href="#">MoviesHere</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/">about</a>
      </li>
      {% if user.is_authenticated %}
      <li>   hello {{user.username}}</li>
       <li class="nav-item">
        <a class="nav-link" href="/logout/">Logout</a>
       </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="/register/">Register</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/login/">Login</a>
      </li>

      <li class="nav-item">
      <a class="btn btn-primary" href="{% url 'firstapp:add'  %}">Add Movie</a><br>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="" role="button" data-toggle="dropdown" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="/movie/7/">Action</a>
          <a class="dropdown-item" href="/movie/12/">comedy</a>
          <a class="dropdown-item" href="/movie/11/">FamilyEntertainer</a>
          <a class="dropdown-item" href="/movie/9/">Thriller</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled">Disabled</a>
      </li>
             {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'searchapp:SearchResult' %}" method="get">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
{% block body %}
{% endblock %}
</body>
</html>

MovieTask/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}

  are you want to delete this movie?

   <input type="submit">
</form>
</body>
</html>

MovieTask/templates/details.html
{% extends 'base.html' %}
{% block body %}


<div class="container">
 <div class="row">
  <div class="col-md-6">
   <img src="{{result.img.url}} " width="500px" height="500px">
  </div>

<div class="col-md-6">
 <h1>{{result.title}}</h1>
<h2>{{result.desc}}</h2>
<h3>{{result.date}}</h3>
    <h3>{{result.actors}}</h3>
    <h3>{{result.url}}</h3>
    <h3>{{result.category}}</h3>
    <h3>{{result.review}}</h3>
    <h3>{{result.rating}}</h3>

<a class="btn btn-danger" href="{% url 'firstapp:update' result.id %}">Update</a><br><br>
 <a class="btn btn-info" href="{% url 'firstapp:delete' result.id %}">Delete</a><br><br>


</div>

 </div>
</div>
{% endblock %}

MovieTask/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}

    <input type="submit">


</form>

MovieTask/templates/home.html
{% extends 'base.html' %}
{% block body  %}


<div class="container ">
     <div class="row">
          {% for i in final %}
          <div class="col-md-4">
          <div class="card  my-3 " style="width:21rem; ">
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="500px" height="500px">
  <div class="card-body mx-3 ">
    <h2 class="card-title">{{i.title}}</h2>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url  'firstapp:details' i.id %}" class="btn btn-primary">View Details</a><br><br>

  </div>
</div>
          </div>
         {% endfor %}
     </div>
</div>

{% endblock %}

MovieTask/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Login Form</h2>
<form method="post">
    {% csrf_token %}
    <input type="text" placeholder="username" name="username"><br><br>
    <input type="password" placeholder="password" name="password"><br><br>
    <input type="submit">

</form>
<body/>
</html>

MovieTask/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Registration Form</h1>
<form method="post">
  {% csrf_token %}
    <input type="text" placeholder="username" name="username"><br><br>
    <input type="text" placeholder="firstname" name="firstname"><br><br>
    <input type="text" placeholder="lastname" name="lastname"><br><br>
    <input type="email" placeholder="email" name="email"><br><br>
    <input type="password" placeholder="password" name="password"><br><br>
    <input type="password"  placeholder="conform password" name="cpassword"><br><br>
    <input type="submit">

</form>

{% for message in messages %}
  {{message}}
{% endfor  %}

</body>
</html>

MovieTask/templates/search.html
<!--{% load static %}-->
<!--{% block metadesccription %}-->
<!--     we have variety of products-->
<!--{% endblock %}-->
<!--{% block title %}-->
<!--   search-->
<!--{% endblock %}-->
{% block content %}
<div>
  <p class="text-center my-search-text">you have searched for: <b>"{{query}}"</b></p>
</div>
<div class="container">
  <div class="row mx-auto">
    {% for product in products %}
    <div class="my-bottom-margin col-9 col-sm-12 col-md-4 xol-lg-4">
  <div class="card text-center" style="min-width:18rem; display:inline-block;">
    <a href="{{product.get_url}}"><img class="card-img-top  my-image" src="{{product.img.url}}" width="200px" height="200px" alt="{{product.name}}"></a>
    <div class="card-body"> <h4>{{product.title}}</h4><p>{{product.category}}</p>
<!--      <p>{{product.price}}</p>-->
<!--      <h4>{{product.name}}</h4>-->
<!--      <p>{{product.price}}</p>-->
    </div>
  </div>
    </div>
      {% empty %}
      <div class="row-mx-auto">
          <p class="text-center my-search-text">0 results found </p>
      </div>
      {% endfor %}
  </div>
</div>
{% endblock %}